### ISSUE TITLE
BUG: literature_fetch_recommendation_api.py stuck if sampling 10 negative articles is not possible

### ISSUE THREAD

**Issue by lilijap** [VirtualPatientEngine/literatureSurvey#47]
**Describe the bug**
Script literature_fetch_recommendation_api.py is stuck, if sampling of negative papers is not possible (not enough papers in another "Topic" provided). It also does not produce an error or stops computations automatically.
See screen shot:
<img width="448" alt="image" src="https://github.com/user-attachments/assets/af80c987-f382-4eab-ba97-69dc3aaa0b1f">

**To Reproduce**
1. Use this .tsv file to run the literature_fetch_recommendation_api.py script locally in your lit. survey repo 
[query.zip](https://github.com/user-attachments/files/16378566/query.zip)
2. The script does not finish or give an error

**Expected behavior**
* give an error that more papers should be provided
* exit the code
* OR not limit # of negative papers to 10 (use any number that is provided)
* OR do not ask for negative papers, because some users just want to have 1 category.

**Screenshots** (optional)

**Desktop (please complete the following information):**
Win11

**Additional context** (optional)
Not limiting negative papers to 10 would increase the accessibility of this repo to unexperienced users.

**Comment by lilijap** [comment]
Tagging @awmulyadi for your reference.

**Comment by awmulyadi** [comment]
This issue is fixed with PR #50
